// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8ckhu_RicwZpyhyB4fsjyXeufY4HMTs',
    appId: '1:506079741946:ios:9c011d3522dd48cb2c4643',
    messagingSenderId: '506079741946',
    projectId: 'fbla-1bf16',
    storageBucket: 'fbla-1bf16.firebasestorage.app',
    iosBundleId: 'com.example.fbla2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8ckhu_RicwZpyhyB4fsjyXeufY4HMTs',
    appId: '1:506079741946:ios:9c011d3522dd48cb2c4643',
    messagingSenderId: '506079741946',
    projectId: 'fbla-1bf16',
    storageBucket: 'fbla-1bf16.firebasestorage.app',
    iosBundleId: 'com.example.fbla2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj9T6zzsn5MoA8mb3u2BoZbzNcoPY3D_g',
    appId: '1:506079741946:web:e670f804bf0af00a2c4643',
    messagingSenderId: '506079741946',
    projectId: 'fbla-1bf16',
    authDomain: 'fbla-1bf16.firebaseapp.com',
    storageBucket: 'fbla-1bf16.firebasestorage.app',
    measurementId: 'G-PFJY7VY06H',
  );
}
